DROP TABLE IF EXISTS opensearch_alert_reconciliation_runs;
DROP TABLE IF EXISTS alert_events;
DROP TABLE IF EXISTS opensearch_alert_deliveries;
ALTER TABLE alerts DROP CONSTRAINT IF EXISTS alerts_receiver_id_fkey;
DROP TABLE IF EXISTS opensearch_alert_receivers;
DELETE FROM alerts WHERE source_type = 'OPENSEARCH_ALERTING';
ALTER TABLE alerts DROP COLUMN IF EXISTS sample_expires_at;
ALTER TABLE alerts DROP COLUMN IF EXISTS last_reconciled_at;
ALTER TABLE alerts DROP COLUMN IF EXISTS last_received_at;
ALTER TABLE alerts DROP COLUMN IF EXISTS dashboard_url;
ALTER TABLE alerts DROP COLUMN IF EXISTS evidence;
ALTER TABLE alerts DROP COLUMN IF EXISTS hit_count;
ALTER TABLE alerts DROP COLUMN IF EXISTS upstream_state;
ALTER TABLE alerts DROP COLUMN IF EXISTS bucket_key;
ALTER TABLE alerts DROP COLUMN IF EXISTS external_alert_id;
ALTER TABLE alerts DROP COLUMN IF EXISTS external_trigger_name;
ALTER TABLE alerts DROP COLUMN IF EXISTS external_trigger_id;
ALTER TABLE alerts DROP COLUMN IF EXISTS external_monitor_type;
ALTER TABLE alerts DROP COLUMN IF EXISTS external_monitor_name;
ALTER TABLE alerts DROP COLUMN IF EXISTS external_monitor_id;
ALTER TABLE alerts DROP COLUMN IF EXISTS receiver_id;
ALTER TABLE alerts DROP COLUMN IF EXISTS service_id;
ALTER TABLE alerts DROP COLUMN IF EXISTS application_id;
ALTER TABLE alerts DROP COLUMN IF EXISTS source_type;
ALTER TABLE alerts ALTER COLUMN monitor_id SET NOT NULL;
ALTER TABLE alerts DROP CONSTRAINT IF EXISTS alerts_state_check;
ALTER TABLE alerts ADD CONSTRAINT alerts_state_check CHECK (state IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED'));
