/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuitesRouteImport } from './routes/suites'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RhythmRouteImport } from './routes/rhythm'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ElfRouteImport } from './routes/elf'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiMonitoringIndexRouteImport } from './routes/ui-monitoring/index'
import { Route as MonitorsIndexRouteImport } from './routes/monitors/index'
import { Route as ElfIndexRouteImport } from './routes/elf/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as UiMonitoringNewRouteImport } from './routes/ui-monitoring/new'
import { Route as UiMonitoringMonitorIdRouteImport } from './routes/ui-monitoring/$monitorId'
import { Route as MonitorsNewRouteImport } from './routes/monitors/new'
import { Route as MonitorsMonitorIdRouteImport } from './routes/monitors/$monitorId'
import { Route as ElfSettingsRouteImport } from './routes/elf/settings'
import { Route as ElfRunsRouteImport } from './routes/elf/runs'
import { Route as ElfQueryIdRouteImport } from './routes/elf/$queryId'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsMarkdownSplatRouteImport } from './routes/docs-markdown/$'
import { Route as DeploymentRunsDeploymentRunIdRouteImport } from './routes/deployment-runs/$deploymentRunId'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications/$applicationId'
import { Route as ApiDocsSearchRouteImport } from './routes/api/docs-search'
import { Route as AlertsAlertIdRouteImport } from './routes/alerts/$alertId'
import { Route as UiMonitoringMonitorIdIndexRouteImport } from './routes/ui-monitoring/$monitorId/index'
import { Route as MonitorsMonitorIdIndexRouteImport } from './routes/monitors/$monitorId/index'
import { Route as UiMonitoringMonitorIdSettingsRouteImport } from './routes/ui-monitoring/$monitorId/settings'
import { Route as UiMonitoringMonitorIdRunsRouteImport } from './routes/ui-monitoring/$monitorId/runs'
import { Route as UiMonitoringMonitorIdMetricsRouteImport } from './routes/ui-monitoring/$monitorId/metrics'
import { Route as UiMonitoringMonitorIdJourneyRouteImport } from './routes/ui-monitoring/$monitorId/journey'
import { Route as UiMonitoringMonitorIdBaselinesRouteImport } from './routes/ui-monitoring/$monitorId/baselines'
import { Route as MonitorsMonitorIdRunsRouteImport } from './routes/monitors/$monitorId/runs'
import { Route as MonitorsMonitorIdRevisionsRouteImport } from './routes/monitors/$monitorId/revisions'
import { Route as MonitorsMonitorIdMetricsRouteImport } from './routes/monitors/$monitorId/metrics'
import { Route as MonitorsMonitorIdEditRouteImport } from './routes/monitors/$monitorId/edit'
import { Route as ElfRunRunIdRouteImport } from './routes/elf/run/$runId'
import { Route as DocsCurrentSplatRouteImport } from './routes/docs/current/$'
import { Route as ApiBrowserArtifactsArtifactIdRouteImport } from './routes/api/browser-artifacts/$artifactId'
import { Route as UiMonitoringMonitorIdRunsIndexRouteImport } from './routes/ui-monitoring/$monitorId/runs/index'
import { Route as MonitorsMonitorIdRunsIndexRouteImport } from './routes/monitors/$monitorId/runs/index'
import { Route as UiMonitoringMonitorIdRunsRunIdRouteImport } from './routes/ui-monitoring/$monitorId/runs/$runId'
import { Route as MonitorsMonitorIdRunsRunIdRouteImport } from './routes/monitors/$monitorId/runs/$runId'

const SuitesRoute = SuitesRouteImport.update({
  id: '/suites',
  path: '/suites',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RhythmRoute = RhythmRouteImport.update({
  id: '/rhythm',
  path: '/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ElfRoute = ElfRouteImport.update({
  id: '/elf',
  path: '/elf',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiMonitoringIndexRoute = UiMonitoringIndexRouteImport.update({
  id: '/ui-monitoring/',
  path: '/ui-monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorsIndexRoute = MonitorsIndexRouteImport.update({
  id: '/monitors/',
  path: '/monitors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElfIndexRoute = ElfIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElfRoute,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicationsRoute,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlertsRoute,
} as any)
const UiMonitoringNewRoute = UiMonitoringNewRouteImport.update({
  id: '/ui-monitoring/new',
  path: '/ui-monitoring/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UiMonitoringMonitorIdRoute = UiMonitoringMonitorIdRouteImport.update({
  id: '/ui-monitoring/$monitorId',
  path: '/ui-monitoring/$monitorId',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorsNewRoute = MonitorsNewRouteImport.update({
  id: '/monitors/new',
  path: '/monitors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorsMonitorIdRoute = MonitorsMonitorIdRouteImport.update({
  id: '/monitors/$monitorId',
  path: '/monitors/$monitorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ElfSettingsRoute = ElfSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ElfRoute,
} as any)
const ElfRunsRoute = ElfRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ElfRoute,
} as any)
const ElfQueryIdRoute = ElfQueryIdRouteImport.update({
  id: '/$queryId',
  path: '/$queryId',
  getParentRoute: () => ElfRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMarkdownSplatRoute = DocsMarkdownSplatRouteImport.update({
  id: '/docs-markdown/$',
  path: '/docs-markdown/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRunsDeploymentRunIdRoute =
  DeploymentRunsDeploymentRunIdRouteImport.update({
    id: '/deployment-runs/$deploymentRunId',
    path: '/deployment-runs/$deploymentRunId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => ApplicationsRoute,
  } as any)
const ApiDocsSearchRoute = ApiDocsSearchRouteImport.update({
  id: '/api/docs-search',
  path: '/api/docs-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdRoute = AlertsAlertIdRouteImport.update({
  id: '/$alertId',
  path: '/$alertId',
  getParentRoute: () => AlertsRoute,
} as any)
const UiMonitoringMonitorIdIndexRoute =
  UiMonitoringMonitorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UiMonitoringMonitorIdRoute,
  } as any)
const MonitorsMonitorIdIndexRoute = MonitorsMonitorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MonitorsMonitorIdRoute,
} as any)
const UiMonitoringMonitorIdSettingsRoute =
  UiMonitoringMonitorIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => UiMonitoringMonitorIdRoute,
  } as any)
const UiMonitoringMonitorIdRunsRoute =
  UiMonitoringMonitorIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => UiMonitoringMonitorIdRoute,
  } as any)
const UiMonitoringMonitorIdMetricsRoute =
  UiMonitoringMonitorIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => UiMonitoringMonitorIdRoute,
  } as any)
const UiMonitoringMonitorIdJourneyRoute =
  UiMonitoringMonitorIdJourneyRouteImport.update({
    id: '/journey',
    path: '/journey',
    getParentRoute: () => UiMonitoringMonitorIdRoute,
  } as any)
const UiMonitoringMonitorIdBaselinesRoute =
  UiMonitoringMonitorIdBaselinesRouteImport.update({
    id: '/baselines',
    path: '/baselines',
    getParentRoute: () => UiMonitoringMonitorIdRoute,
  } as any)
const MonitorsMonitorIdRunsRoute = MonitorsMonitorIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => MonitorsMonitorIdRoute,
} as any)
const MonitorsMonitorIdRevisionsRoute =
  MonitorsMonitorIdRevisionsRouteImport.update({
    id: '/revisions',
    path: '/revisions',
    getParentRoute: () => MonitorsMonitorIdRoute,
  } as any)
const MonitorsMonitorIdMetricsRoute =
  MonitorsMonitorIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => MonitorsMonitorIdRoute,
  } as any)
const MonitorsMonitorIdEditRoute = MonitorsMonitorIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MonitorsMonitorIdRoute,
} as any)
const ElfRunRunIdRoute = ElfRunRunIdRouteImport.update({
  id: '/run/$runId',
  path: '/run/$runId',
  getParentRoute: () => ElfRoute,
} as any)
const DocsCurrentSplatRoute = DocsCurrentSplatRouteImport.update({
  id: '/docs/current/$',
  path: '/docs/current/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowserArtifactsArtifactIdRoute =
  ApiBrowserArtifactsArtifactIdRouteImport.update({
    id: '/api/browser-artifacts/$artifactId',
    path: '/api/browser-artifacts/$artifactId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UiMonitoringMonitorIdRunsIndexRoute =
  UiMonitoringMonitorIdRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UiMonitoringMonitorIdRunsRoute,
  } as any)
const MonitorsMonitorIdRunsIndexRoute =
  MonitorsMonitorIdRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MonitorsMonitorIdRunsRoute,
  } as any)
const UiMonitoringMonitorIdRunsRunIdRoute =
  UiMonitoringMonitorIdRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => UiMonitoringMonitorIdRunsRoute,
  } as any)
const MonitorsMonitorIdRunsRunIdRoute =
  MonitorsMonitorIdRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => MonitorsMonitorIdRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/applications': typeof ApplicationsRouteWithChildren
  '/audit': typeof AuditRoute
  '/configuration': typeof ConfigurationRoute
  '/elf': typeof ElfRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/rhythm': typeof RhythmRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suites': typeof SuitesRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/api/docs-search': typeof ApiDocsSearchRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/deployment-runs/$deploymentRunId': typeof DeploymentRunsDeploymentRunIdRoute
  '/docs-markdown/$': typeof DocsMarkdownSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/elf/$queryId': typeof ElfQueryIdRoute
  '/elf/runs': typeof ElfRunsRoute
  '/elf/settings': typeof ElfSettingsRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRouteWithChildren
  '/monitors/new': typeof MonitorsNewRoute
  '/ui-monitoring/$monitorId': typeof UiMonitoringMonitorIdRouteWithChildren
  '/ui-monitoring/new': typeof UiMonitoringNewRoute
  '/alerts/': typeof AlertsIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/elf/': typeof ElfIndexRoute
  '/monitors/': typeof MonitorsIndexRoute
  '/ui-monitoring/': typeof UiMonitoringIndexRoute
  '/api/browser-artifacts/$artifactId': typeof ApiBrowserArtifactsArtifactIdRoute
  '/docs/current/$': typeof DocsCurrentSplatRoute
  '/elf/run/$runId': typeof ElfRunRunIdRoute
  '/monitors/$monitorId/edit': typeof MonitorsMonitorIdEditRoute
  '/monitors/$monitorId/metrics': typeof MonitorsMonitorIdMetricsRoute
  '/monitors/$monitorId/revisions': typeof MonitorsMonitorIdRevisionsRoute
  '/monitors/$monitorId/runs': typeof MonitorsMonitorIdRunsRouteWithChildren
  '/ui-monitoring/$monitorId/baselines': typeof UiMonitoringMonitorIdBaselinesRoute
  '/ui-monitoring/$monitorId/journey': typeof UiMonitoringMonitorIdJourneyRoute
  '/ui-monitoring/$monitorId/metrics': typeof UiMonitoringMonitorIdMetricsRoute
  '/ui-monitoring/$monitorId/runs': typeof UiMonitoringMonitorIdRunsRouteWithChildren
  '/ui-monitoring/$monitorId/settings': typeof UiMonitoringMonitorIdSettingsRoute
  '/monitors/$monitorId/': typeof MonitorsMonitorIdIndexRoute
  '/ui-monitoring/$monitorId/': typeof UiMonitoringMonitorIdIndexRoute
  '/monitors/$monitorId/runs/$runId': typeof MonitorsMonitorIdRunsRunIdRoute
  '/ui-monitoring/$monitorId/runs/$runId': typeof UiMonitoringMonitorIdRunsRunIdRoute
  '/monitors/$monitorId/runs/': typeof MonitorsMonitorIdRunsIndexRoute
  '/ui-monitoring/$monitorId/runs/': typeof UiMonitoringMonitorIdRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/audit': typeof AuditRoute
  '/configuration': typeof ConfigurationRoute
  '/healthz': typeof HealthzRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/rhythm': typeof RhythmRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suites': typeof SuitesRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/api/docs-search': typeof ApiDocsSearchRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/deployment-runs/$deploymentRunId': typeof DeploymentRunsDeploymentRunIdRoute
  '/docs-markdown/$': typeof DocsMarkdownSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/elf/$queryId': typeof ElfQueryIdRoute
  '/elf/runs': typeof ElfRunsRoute
  '/elf/settings': typeof ElfSettingsRoute
  '/monitors/new': typeof MonitorsNewRoute
  '/ui-monitoring/new': typeof UiMonitoringNewRoute
  '/alerts': typeof AlertsIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/elf': typeof ElfIndexRoute
  '/monitors': typeof MonitorsIndexRoute
  '/ui-monitoring': typeof UiMonitoringIndexRoute
  '/api/browser-artifacts/$artifactId': typeof ApiBrowserArtifactsArtifactIdRoute
  '/docs/current/$': typeof DocsCurrentSplatRoute
  '/elf/run/$runId': typeof ElfRunRunIdRoute
  '/monitors/$monitorId/edit': typeof MonitorsMonitorIdEditRoute
  '/monitors/$monitorId/metrics': typeof MonitorsMonitorIdMetricsRoute
  '/monitors/$monitorId/revisions': typeof MonitorsMonitorIdRevisionsRoute
  '/ui-monitoring/$monitorId/baselines': typeof UiMonitoringMonitorIdBaselinesRoute
  '/ui-monitoring/$monitorId/journey': typeof UiMonitoringMonitorIdJourneyRoute
  '/ui-monitoring/$monitorId/metrics': typeof UiMonitoringMonitorIdMetricsRoute
  '/ui-monitoring/$monitorId/settings': typeof UiMonitoringMonitorIdSettingsRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdIndexRoute
  '/ui-monitoring/$monitorId': typeof UiMonitoringMonitorIdIndexRoute
  '/monitors/$monitorId/runs/$runId': typeof MonitorsMonitorIdRunsRunIdRoute
  '/ui-monitoring/$monitorId/runs/$runId': typeof UiMonitoringMonitorIdRunsRunIdRoute
  '/monitors/$monitorId/runs': typeof MonitorsMonitorIdRunsIndexRoute
  '/ui-monitoring/$monitorId/runs': typeof UiMonitoringMonitorIdRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/applications': typeof ApplicationsRouteWithChildren
  '/audit': typeof AuditRoute
  '/configuration': typeof ConfigurationRoute
  '/elf': typeof ElfRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/rhythm': typeof RhythmRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suites': typeof SuitesRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/api/docs-search': typeof ApiDocsSearchRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/deployment-runs/$deploymentRunId': typeof DeploymentRunsDeploymentRunIdRoute
  '/docs-markdown/$': typeof DocsMarkdownSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/elf/$queryId': typeof ElfQueryIdRoute
  '/elf/runs': typeof ElfRunsRoute
  '/elf/settings': typeof ElfSettingsRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRouteWithChildren
  '/monitors/new': typeof MonitorsNewRoute
  '/ui-monitoring/$monitorId': typeof UiMonitoringMonitorIdRouteWithChildren
  '/ui-monitoring/new': typeof UiMonitoringNewRoute
  '/alerts/': typeof AlertsIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/elf/': typeof ElfIndexRoute
  '/monitors/': typeof MonitorsIndexRoute
  '/ui-monitoring/': typeof UiMonitoringIndexRoute
  '/api/browser-artifacts/$artifactId': typeof ApiBrowserArtifactsArtifactIdRoute
  '/docs/current/$': typeof DocsCurrentSplatRoute
  '/elf/run/$runId': typeof ElfRunRunIdRoute
  '/monitors/$monitorId/edit': typeof MonitorsMonitorIdEditRoute
  '/monitors/$monitorId/metrics': typeof MonitorsMonitorIdMetricsRoute
  '/monitors/$monitorId/revisions': typeof MonitorsMonitorIdRevisionsRoute
  '/monitors/$monitorId/runs': typeof MonitorsMonitorIdRunsRouteWithChildren
  '/ui-monitoring/$monitorId/baselines': typeof UiMonitoringMonitorIdBaselinesRoute
  '/ui-monitoring/$monitorId/journey': typeof UiMonitoringMonitorIdJourneyRoute
  '/ui-monitoring/$monitorId/metrics': typeof UiMonitoringMonitorIdMetricsRoute
  '/ui-monitoring/$monitorId/runs': typeof UiMonitoringMonitorIdRunsRouteWithChildren
  '/ui-monitoring/$monitorId/settings': typeof UiMonitoringMonitorIdSettingsRoute
  '/monitors/$monitorId/': typeof MonitorsMonitorIdIndexRoute
  '/ui-monitoring/$monitorId/': typeof UiMonitoringMonitorIdIndexRoute
  '/monitors/$monitorId/runs/$runId': typeof MonitorsMonitorIdRunsRunIdRoute
  '/ui-monitoring/$monitorId/runs/$runId': typeof UiMonitoringMonitorIdRunsRunIdRoute
  '/monitors/$monitorId/runs/': typeof MonitorsMonitorIdRunsIndexRoute
  '/ui-monitoring/$monitorId/runs/': typeof UiMonitoringMonitorIdRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/alerts'
    | '/applications'
    | '/audit'
    | '/configuration'
    | '/elf'
    | '/healthz'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/rhythm'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/suites'
    | '/alerts/$alertId'
    | '/api/docs-search'
    | '/applications/$applicationId'
    | '/deployment-runs/$deploymentRunId'
    | '/docs-markdown/$'
    | '/docs/$'
    | '/elf/$queryId'
    | '/elf/runs'
    | '/elf/settings'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/ui-monitoring/$monitorId'
    | '/ui-monitoring/new'
    | '/alerts/'
    | '/applications/'
    | '/elf/'
    | '/monitors/'
    | '/ui-monitoring/'
    | '/api/browser-artifacts/$artifactId'
    | '/docs/current/$'
    | '/elf/run/$runId'
    | '/monitors/$monitorId/edit'
    | '/monitors/$monitorId/metrics'
    | '/monitors/$monitorId/revisions'
    | '/monitors/$monitorId/runs'
    | '/ui-monitoring/$monitorId/baselines'
    | '/ui-monitoring/$monitorId/journey'
    | '/ui-monitoring/$monitorId/metrics'
    | '/ui-monitoring/$monitorId/runs'
    | '/ui-monitoring/$monitorId/settings'
    | '/monitors/$monitorId/'
    | '/ui-monitoring/$monitorId/'
    | '/monitors/$monitorId/runs/$runId'
    | '/ui-monitoring/$monitorId/runs/$runId'
    | '/monitors/$monitorId/runs/'
    | '/ui-monitoring/$monitorId/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/audit'
    | '/configuration'
    | '/healthz'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/rhythm'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/suites'
    | '/alerts/$alertId'
    | '/api/docs-search'
    | '/applications/$applicationId'
    | '/deployment-runs/$deploymentRunId'
    | '/docs-markdown/$'
    | '/docs/$'
    | '/elf/$queryId'
    | '/elf/runs'
    | '/elf/settings'
    | '/monitors/new'
    | '/ui-monitoring/new'
    | '/alerts'
    | '/applications'
    | '/elf'
    | '/monitors'
    | '/ui-monitoring'
    | '/api/browser-artifacts/$artifactId'
    | '/docs/current/$'
    | '/elf/run/$runId'
    | '/monitors/$monitorId/edit'
    | '/monitors/$monitorId/metrics'
    | '/monitors/$monitorId/revisions'
    | '/ui-monitoring/$monitorId/baselines'
    | '/ui-monitoring/$monitorId/journey'
    | '/ui-monitoring/$monitorId/metrics'
    | '/ui-monitoring/$monitorId/settings'
    | '/monitors/$monitorId'
    | '/ui-monitoring/$monitorId'
    | '/monitors/$monitorId/runs/$runId'
    | '/ui-monitoring/$monitorId/runs/$runId'
    | '/monitors/$monitorId/runs'
    | '/ui-monitoring/$monitorId/runs'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/alerts'
    | '/applications'
    | '/audit'
    | '/configuration'
    | '/elf'
    | '/healthz'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/rhythm'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/suites'
    | '/alerts/$alertId'
    | '/api/docs-search'
    | '/applications/$applicationId'
    | '/deployment-runs/$deploymentRunId'
    | '/docs-markdown/$'
    | '/docs/$'
    | '/elf/$queryId'
    | '/elf/runs'
    | '/elf/settings'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/ui-monitoring/$monitorId'
    | '/ui-monitoring/new'
    | '/alerts/'
    | '/applications/'
    | '/elf/'
    | '/monitors/'
    | '/ui-monitoring/'
    | '/api/browser-artifacts/$artifactId'
    | '/docs/current/$'
    | '/elf/run/$runId'
    | '/monitors/$monitorId/edit'
    | '/monitors/$monitorId/metrics'
    | '/monitors/$monitorId/revisions'
    | '/monitors/$monitorId/runs'
    | '/ui-monitoring/$monitorId/baselines'
    | '/ui-monitoring/$monitorId/journey'
    | '/ui-monitoring/$monitorId/metrics'
    | '/ui-monitoring/$monitorId/runs'
    | '/ui-monitoring/$monitorId/settings'
    | '/monitors/$monitorId/'
    | '/ui-monitoring/$monitorId/'
    | '/monitors/$monitorId/runs/$runId'
    | '/ui-monitoring/$monitorId/runs/$runId'
    | '/monitors/$monitorId/runs/'
    | '/ui-monitoring/$monitorId/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AlertsRoute: typeof AlertsRouteWithChildren
  ApplicationsRoute: typeof ApplicationsRouteWithChildren
  AuditRoute: typeof AuditRoute
  ConfigurationRoute: typeof ConfigurationRoute
  ElfRoute: typeof ElfRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RhythmRoute: typeof RhythmRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuitesRoute: typeof SuitesRoute
  ApiDocsSearchRoute: typeof ApiDocsSearchRoute
  DeploymentRunsDeploymentRunIdRoute: typeof DeploymentRunsDeploymentRunIdRoute
  DocsMarkdownSplatRoute: typeof DocsMarkdownSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  MonitorsMonitorIdRoute: typeof MonitorsMonitorIdRouteWithChildren
  MonitorsNewRoute: typeof MonitorsNewRoute
  UiMonitoringMonitorIdRoute: typeof UiMonitoringMonitorIdRouteWithChildren
  UiMonitoringNewRoute: typeof UiMonitoringNewRoute
  MonitorsIndexRoute: typeof MonitorsIndexRoute
  UiMonitoringIndexRoute: typeof UiMonitoringIndexRoute
  ApiBrowserArtifactsArtifactIdRoute: typeof ApiBrowserArtifactsArtifactIdRoute
  DocsCurrentSplatRoute: typeof DocsCurrentSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suites': {
      id: '/suites'
      path: '/suites'
      fullPath: '/suites'
      preLoaderRoute: typeof SuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhythm': {
      id: '/rhythm'
      path: '/rhythm'
      fullPath: '/rhythm'
      preLoaderRoute: typeof RhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elf': {
      id: '/elf'
      path: '/elf'
      fullPath: '/elf'
      preLoaderRoute: typeof ElfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-monitoring/': {
      id: '/ui-monitoring/'
      path: '/ui-monitoring'
      fullPath: '/ui-monitoring/'
      preLoaderRoute: typeof UiMonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors/': {
      id: '/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof MonitorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elf/': {
      id: '/elf/'
      path: '/'
      fullPath: '/elf/'
      preLoaderRoute: typeof ElfIndexRouteImport
      parentRoute: typeof ElfRoute
    }
    '/applications/': {
      id: '/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/ui-monitoring/new': {
      id: '/ui-monitoring/new'
      path: '/ui-monitoring/new'
      fullPath: '/ui-monitoring/new'
      preLoaderRoute: typeof UiMonitoringNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-monitoring/$monitorId': {
      id: '/ui-monitoring/$monitorId'
      path: '/ui-monitoring/$monitorId'
      fullPath: '/ui-monitoring/$monitorId'
      preLoaderRoute: typeof UiMonitoringMonitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors/new': {
      id: '/monitors/new'
      path: '/monitors/new'
      fullPath: '/monitors/new'
      preLoaderRoute: typeof MonitorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors/$monitorId': {
      id: '/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof MonitorsMonitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elf/settings': {
      id: '/elf/settings'
      path: '/settings'
      fullPath: '/elf/settings'
      preLoaderRoute: typeof ElfSettingsRouteImport
      parentRoute: typeof ElfRoute
    }
    '/elf/runs': {
      id: '/elf/runs'
      path: '/runs'
      fullPath: '/elf/runs'
      preLoaderRoute: typeof ElfRunsRouteImport
      parentRoute: typeof ElfRoute
    }
    '/elf/$queryId': {
      id: '/elf/$queryId'
      path: '/$queryId'
      fullPath: '/elf/$queryId'
      preLoaderRoute: typeof ElfQueryIdRouteImport
      parentRoute: typeof ElfRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-markdown/$': {
      id: '/docs-markdown/$'
      path: '/docs-markdown/$'
      fullPath: '/docs-markdown/$'
      preLoaderRoute: typeof DocsMarkdownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment-runs/$deploymentRunId': {
      id: '/deployment-runs/$deploymentRunId'
      path: '/deployment-runs/$deploymentRunId'
      fullPath: '/deployment-runs/$deploymentRunId'
      preLoaderRoute: typeof DeploymentRunsDeploymentRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/api/docs-search': {
      id: '/api/docs-search'
      path: '/api/docs-search'
      fullPath: '/api/docs-search'
      preLoaderRoute: typeof ApiDocsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId': {
      id: '/alerts/$alertId'
      path: '/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/ui-monitoring/$monitorId/': {
      id: '/ui-monitoring/$monitorId/'
      path: '/'
      fullPath: '/ui-monitoring/$monitorId/'
      preLoaderRoute: typeof UiMonitoringMonitorIdIndexRouteImport
      parentRoute: typeof UiMonitoringMonitorIdRoute
    }
    '/monitors/$monitorId/': {
      id: '/monitors/$monitorId/'
      path: '/'
      fullPath: '/monitors/$monitorId/'
      preLoaderRoute: typeof MonitorsMonitorIdIndexRouteImport
      parentRoute: typeof MonitorsMonitorIdRoute
    }
    '/ui-monitoring/$monitorId/settings': {
      id: '/ui-monitoring/$monitorId/settings'
      path: '/settings'
      fullPath: '/ui-monitoring/$monitorId/settings'
      preLoaderRoute: typeof UiMonitoringMonitorIdSettingsRouteImport
      parentRoute: typeof UiMonitoringMonitorIdRoute
    }
    '/ui-monitoring/$monitorId/runs': {
      id: '/ui-monitoring/$monitorId/runs'
      path: '/runs'
      fullPath: '/ui-monitoring/$monitorId/runs'
      preLoaderRoute: typeof UiMonitoringMonitorIdRunsRouteImport
      parentRoute: typeof UiMonitoringMonitorIdRoute
    }
    '/ui-monitoring/$monitorId/metrics': {
      id: '/ui-monitoring/$monitorId/metrics'
      path: '/metrics'
      fullPath: '/ui-monitoring/$monitorId/metrics'
      preLoaderRoute: typeof UiMonitoringMonitorIdMetricsRouteImport
      parentRoute: typeof UiMonitoringMonitorIdRoute
    }
    '/ui-monitoring/$monitorId/journey': {
      id: '/ui-monitoring/$monitorId/journey'
      path: '/journey'
      fullPath: '/ui-monitoring/$monitorId/journey'
      preLoaderRoute: typeof UiMonitoringMonitorIdJourneyRouteImport
      parentRoute: typeof UiMonitoringMonitorIdRoute
    }
    '/ui-monitoring/$monitorId/baselines': {
      id: '/ui-monitoring/$monitorId/baselines'
      path: '/baselines'
      fullPath: '/ui-monitoring/$monitorId/baselines'
      preLoaderRoute: typeof UiMonitoringMonitorIdBaselinesRouteImport
      parentRoute: typeof UiMonitoringMonitorIdRoute
    }
    '/monitors/$monitorId/runs': {
      id: '/monitors/$monitorId/runs'
      path: '/runs'
      fullPath: '/monitors/$monitorId/runs'
      preLoaderRoute: typeof MonitorsMonitorIdRunsRouteImport
      parentRoute: typeof MonitorsMonitorIdRoute
    }
    '/monitors/$monitorId/revisions': {
      id: '/monitors/$monitorId/revisions'
      path: '/revisions'
      fullPath: '/monitors/$monitorId/revisions'
      preLoaderRoute: typeof MonitorsMonitorIdRevisionsRouteImport
      parentRoute: typeof MonitorsMonitorIdRoute
    }
    '/monitors/$monitorId/metrics': {
      id: '/monitors/$monitorId/metrics'
      path: '/metrics'
      fullPath: '/monitors/$monitorId/metrics'
      preLoaderRoute: typeof MonitorsMonitorIdMetricsRouteImport
      parentRoute: typeof MonitorsMonitorIdRoute
    }
    '/monitors/$monitorId/edit': {
      id: '/monitors/$monitorId/edit'
      path: '/edit'
      fullPath: '/monitors/$monitorId/edit'
      preLoaderRoute: typeof MonitorsMonitorIdEditRouteImport
      parentRoute: typeof MonitorsMonitorIdRoute
    }
    '/elf/run/$runId': {
      id: '/elf/run/$runId'
      path: '/run/$runId'
      fullPath: '/elf/run/$runId'
      preLoaderRoute: typeof ElfRunRunIdRouteImport
      parentRoute: typeof ElfRoute
    }
    '/docs/current/$': {
      id: '/docs/current/$'
      path: '/docs/current/$'
      fullPath: '/docs/current/$'
      preLoaderRoute: typeof DocsCurrentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browser-artifacts/$artifactId': {
      id: '/api/browser-artifacts/$artifactId'
      path: '/api/browser-artifacts/$artifactId'
      fullPath: '/api/browser-artifacts/$artifactId'
      preLoaderRoute: typeof ApiBrowserArtifactsArtifactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-monitoring/$monitorId/runs/': {
      id: '/ui-monitoring/$monitorId/runs/'
      path: '/'
      fullPath: '/ui-monitoring/$monitorId/runs/'
      preLoaderRoute: typeof UiMonitoringMonitorIdRunsIndexRouteImport
      parentRoute: typeof UiMonitoringMonitorIdRunsRoute
    }
    '/monitors/$monitorId/runs/': {
      id: '/monitors/$monitorId/runs/'
      path: '/'
      fullPath: '/monitors/$monitorId/runs/'
      preLoaderRoute: typeof MonitorsMonitorIdRunsIndexRouteImport
      parentRoute: typeof MonitorsMonitorIdRunsRoute
    }
    '/ui-monitoring/$monitorId/runs/$runId': {
      id: '/ui-monitoring/$monitorId/runs/$runId'
      path: '/$runId'
      fullPath: '/ui-monitoring/$monitorId/runs/$runId'
      preLoaderRoute: typeof UiMonitoringMonitorIdRunsRunIdRouteImport
      parentRoute: typeof UiMonitoringMonitorIdRunsRoute
    }
    '/monitors/$monitorId/runs/$runId': {
      id: '/monitors/$monitorId/runs/$runId'
      path: '/$runId'
      fullPath: '/monitors/$monitorId/runs/$runId'
      preLoaderRoute: typeof MonitorsMonitorIdRunsRunIdRouteImport
      parentRoute: typeof MonitorsMonitorIdRunsRoute
    }
  }
}

interface AlertsRouteChildren {
  AlertsAlertIdRoute: typeof AlertsAlertIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
}

const AlertsRouteChildren: AlertsRouteChildren = {
  AlertsAlertIdRoute: AlertsAlertIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
}

const AlertsRouteWithChildren =
  AlertsRoute._addFileChildren(AlertsRouteChildren)

interface ApplicationsRouteChildren {
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
}

const ApplicationsRouteChildren: ApplicationsRouteChildren = {
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
}

const ApplicationsRouteWithChildren = ApplicationsRoute._addFileChildren(
  ApplicationsRouteChildren,
)

interface ElfRouteChildren {
  ElfQueryIdRoute: typeof ElfQueryIdRoute
  ElfRunsRoute: typeof ElfRunsRoute
  ElfSettingsRoute: typeof ElfSettingsRoute
  ElfIndexRoute: typeof ElfIndexRoute
  ElfRunRunIdRoute: typeof ElfRunRunIdRoute
}

const ElfRouteChildren: ElfRouteChildren = {
  ElfQueryIdRoute: ElfQueryIdRoute,
  ElfRunsRoute: ElfRunsRoute,
  ElfSettingsRoute: ElfSettingsRoute,
  ElfIndexRoute: ElfIndexRoute,
  ElfRunRunIdRoute: ElfRunRunIdRoute,
}

const ElfRouteWithChildren = ElfRoute._addFileChildren(ElfRouteChildren)

interface MonitorsMonitorIdRunsRouteChildren {
  MonitorsMonitorIdRunsRunIdRoute: typeof MonitorsMonitorIdRunsRunIdRoute
  MonitorsMonitorIdRunsIndexRoute: typeof MonitorsMonitorIdRunsIndexRoute
}

const MonitorsMonitorIdRunsRouteChildren: MonitorsMonitorIdRunsRouteChildren = {
  MonitorsMonitorIdRunsRunIdRoute: MonitorsMonitorIdRunsRunIdRoute,
  MonitorsMonitorIdRunsIndexRoute: MonitorsMonitorIdRunsIndexRoute,
}

const MonitorsMonitorIdRunsRouteWithChildren =
  MonitorsMonitorIdRunsRoute._addFileChildren(
    MonitorsMonitorIdRunsRouteChildren,
  )

interface MonitorsMonitorIdRouteChildren {
  MonitorsMonitorIdEditRoute: typeof MonitorsMonitorIdEditRoute
  MonitorsMonitorIdMetricsRoute: typeof MonitorsMonitorIdMetricsRoute
  MonitorsMonitorIdRevisionsRoute: typeof MonitorsMonitorIdRevisionsRoute
  MonitorsMonitorIdRunsRoute: typeof MonitorsMonitorIdRunsRouteWithChildren
  MonitorsMonitorIdIndexRoute: typeof MonitorsMonitorIdIndexRoute
}

const MonitorsMonitorIdRouteChildren: MonitorsMonitorIdRouteChildren = {
  MonitorsMonitorIdEditRoute: MonitorsMonitorIdEditRoute,
  MonitorsMonitorIdMetricsRoute: MonitorsMonitorIdMetricsRoute,
  MonitorsMonitorIdRevisionsRoute: MonitorsMonitorIdRevisionsRoute,
  MonitorsMonitorIdRunsRoute: MonitorsMonitorIdRunsRouteWithChildren,
  MonitorsMonitorIdIndexRoute: MonitorsMonitorIdIndexRoute,
}

const MonitorsMonitorIdRouteWithChildren =
  MonitorsMonitorIdRoute._addFileChildren(MonitorsMonitorIdRouteChildren)

interface UiMonitoringMonitorIdRunsRouteChildren {
  UiMonitoringMonitorIdRunsRunIdRoute: typeof UiMonitoringMonitorIdRunsRunIdRoute
  UiMonitoringMonitorIdRunsIndexRoute: typeof UiMonitoringMonitorIdRunsIndexRoute
}

const UiMonitoringMonitorIdRunsRouteChildren: UiMonitoringMonitorIdRunsRouteChildren =
  {
    UiMonitoringMonitorIdRunsRunIdRoute: UiMonitoringMonitorIdRunsRunIdRoute,
    UiMonitoringMonitorIdRunsIndexRoute: UiMonitoringMonitorIdRunsIndexRoute,
  }

const UiMonitoringMonitorIdRunsRouteWithChildren =
  UiMonitoringMonitorIdRunsRoute._addFileChildren(
    UiMonitoringMonitorIdRunsRouteChildren,
  )

interface UiMonitoringMonitorIdRouteChildren {
  UiMonitoringMonitorIdBaselinesRoute: typeof UiMonitoringMonitorIdBaselinesRoute
  UiMonitoringMonitorIdJourneyRoute: typeof UiMonitoringMonitorIdJourneyRoute
  UiMonitoringMonitorIdMetricsRoute: typeof UiMonitoringMonitorIdMetricsRoute
  UiMonitoringMonitorIdRunsRoute: typeof UiMonitoringMonitorIdRunsRouteWithChildren
  UiMonitoringMonitorIdSettingsRoute: typeof UiMonitoringMonitorIdSettingsRoute
  UiMonitoringMonitorIdIndexRoute: typeof UiMonitoringMonitorIdIndexRoute
}

const UiMonitoringMonitorIdRouteChildren: UiMonitoringMonitorIdRouteChildren = {
  UiMonitoringMonitorIdBaselinesRoute: UiMonitoringMonitorIdBaselinesRoute,
  UiMonitoringMonitorIdJourneyRoute: UiMonitoringMonitorIdJourneyRoute,
  UiMonitoringMonitorIdMetricsRoute: UiMonitoringMonitorIdMetricsRoute,
  UiMonitoringMonitorIdRunsRoute: UiMonitoringMonitorIdRunsRouteWithChildren,
  UiMonitoringMonitorIdSettingsRoute: UiMonitoringMonitorIdSettingsRoute,
  UiMonitoringMonitorIdIndexRoute: UiMonitoringMonitorIdIndexRoute,
}

const UiMonitoringMonitorIdRouteWithChildren =
  UiMonitoringMonitorIdRoute._addFileChildren(
    UiMonitoringMonitorIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AlertsRoute: AlertsRouteWithChildren,
  ApplicationsRoute: ApplicationsRouteWithChildren,
  AuditRoute: AuditRoute,
  ConfigurationRoute: ConfigurationRoute,
  ElfRoute: ElfRouteWithChildren,
  HealthzRoute: HealthzRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RhythmRoute: RhythmRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuitesRoute: SuitesRoute,
  ApiDocsSearchRoute: ApiDocsSearchRoute,
  DeploymentRunsDeploymentRunIdRoute: DeploymentRunsDeploymentRunIdRoute,
  DocsMarkdownSplatRoute: DocsMarkdownSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  MonitorsMonitorIdRoute: MonitorsMonitorIdRouteWithChildren,
  MonitorsNewRoute: MonitorsNewRoute,
  UiMonitoringMonitorIdRoute: UiMonitoringMonitorIdRouteWithChildren,
  UiMonitoringNewRoute: UiMonitoringNewRoute,
  MonitorsIndexRoute: MonitorsIndexRoute,
  UiMonitoringIndexRoute: UiMonitoringIndexRoute,
  ApiBrowserArtifactsArtifactIdRoute: ApiBrowserArtifactsArtifactIdRoute,
  DocsCurrentSplatRoute: DocsCurrentSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
