changeLogFile=dbscripts/main_changelog.xml
liquibase.showBanner=false
liquibase.hub.mode=off
liquibase.command.defaultSchemaName=public
liquibase.command.validate.showSummary=summary
liquibase.command.update.showSummary=summary

