apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rhythm-api
spec:
  minAvailable: 1
  selector: { matchLabels: { app.kubernetes.io/name: rhythm-api } }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rhythm-api-worker
spec:
  minAvailable: 3
  selector: { matchLabels: { app.kubernetes.io/name: rhythm-api-worker } }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rhythm-scheduler
spec:
  minAvailable: 1
  selector: { matchLabels: { app.kubernetes.io/name: rhythm-scheduler } }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rhythm-script-runner
spec:
  minAvailable: 1
  selector: { matchLabels: { app.kubernetes.io/name: rhythm-script-runner } }
